{{- if .Values.customSloConfig.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sloth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sloth.labels" . | nindent 4 }}
data:
  window.yaml: |
    {{- toYaml .Values.customSloConfig.data | nindent 4 }}
{{- end }}
