{{- if .Values.metrics.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "sloth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "sloth.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "sloth.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
{{- end }}